spring:
  datasource:
    url: jdbc:mysql://maglev.proxy.rlwy.net:41424/railway
    username: root
    password: bpGeCfDFrThHjJQaOinrSPVhaTGkEhVI
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true